name: Check spy versions

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-spy-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Verify spy version sync
        run: ./ci/check-spy-versions.sh
