name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    name: cargo fmt --check
    runs-on: ubuntu-x64-small
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          components: rustfmt

      - name: Run formatting check
        run: make rust/fmt/check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-x64-small
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          components: clippy

      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- --deny warnings

  test:
    name: cargo test (${{ matrix.package }})
    runs-on: ubuntu-x64-small
    strategy:
      fail-fast: false
      matrix:
        package:
          - pyroscope
          - pyroscope_python_extension
          - ffiruby
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --locked -p ${{ matrix.package }}
