name: Publish Python to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-python:
    permissions:
      id-token: write
    name: "Python"
    runs-on: ubuntu-x64-small
    if: "startsWith(github.event.release.tag_name, 'python-')"
    steps:
      - uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # 1.12
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
