name: Publish to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-pyroscope:
    name: pyroscope-lib
    runs-on: ubuntu-x64-small
    if: "startsWith(github.event.release.tag_name, 'lib-')"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: 1.85.0
      - name: publish pyroscope crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
  publish-python:
    permissions:
      id-token: write
    name: "Python" 
    runs-on: ubuntu-x64-small
    if: "startsWith(github.event.release.tag_name, 'python-')"
    steps:
      - uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # 1.12
        with: 
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
          tarBall: false 
          zipBall: false 
          out-file-path: "dist"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

