name: Python Release

on:
  push:
    tags:
      - 'python-*'

jobs:
  python-release-linux:
    permissions:
      contents: write
    needs: [ 'python-release' ]
    name: Release python linux amd64
    runs-on: ubuntu-x64-large
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: make wheel/linux/amd64
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.sha }}-python-amd64
          path: dist/*

      - name: Upload release artifact
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: true
          files: dist/pyroscope*.whl
  python-release-linux-arm:
    permissions:
      contents: write
    needs: [ 'python-release' ]
    name: Release python linux arm64
    runs-on: ubuntu-arm64-large
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: make wheel/linux/arm64
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.sha }}-python-arm64
          path: dist/*

      - name: Upload release artifact
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: true
          files: dist/pyroscope*.whl
  python-release-macos:
    permissions:
      contents: write
    needs: [ 'python-release' ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos-version: "14"
            target: x86_64-apple-darwin
            mk-arch: amd64
          - macos-version: "14"
            target: aarch64-apple-darwin
            mk-arch: arm64

    name: macOS - ${{ matrix.target }}
    runs-on: macos-${{ matrix.macos-version }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: 1.85.0
          target: ${{ matrix.target }}

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # 6.2.0
        with:
          python-version: 3.11

      - run: pip install build wheel
      - run: make wheel/mac/${{ matrix.mk-arch }}

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.sha }}-python-macos-${{ matrix.target }}
          path: dist/*

      - name: Upload release artifact
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: true
          files: dist/pyroscope*.whl
  python-release-sdist:
    permissions:
      contents: write
    needs: [ 'python-release' ]
    name: sdist
    runs-on: ubuntu-x64-small

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # 6.2.0
        with:
          python-version: 3.9
      - run: python -m pip install build
      - run: python -m build --sdist
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.sha }}-python-sdist
          path: dist/*

      - name: Upload release artifact
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: true
          files: dist/pyroscope-io-*.tar.gz
  python-release:
    permissions:
      contents: write
    name: Python Package
    runs-on: ubuntu-x64-small
    steps:
      - id: auto-release
        uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0" # v1.2.1 TODO(korniltsev): get rid of this, this one is unmaintained
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          title: "Python Package: ${{ github.ref_name }}"
          draft: true
          prerelease: false
